### ISSUE TITLE
ToListAsync() kills the connection when over 10k results

### ISSUE THREAD

**Issue by VagyokC4** [redis/redis-om-dotnet#215]
@slorello89  When querying a collection that has more than 10k results, the client times out and fails to return any results.  The connection is now dead and the app must be restarted.

Sample code to reproduce the issue:
```csharp
var redisCollection = redisConnectionProvider.RedisCollection<Customer>(false);
await redisConnectionProvider.Connection.CreateIndexAsync(typeof(Customer));

// Seed Data with more than 10k results
await Task.WhenAll(Enumerable.Range(1, 15000).Select(e =>
	redisCollection.InsertAsync(new Customer
	{
		FirstName = "Test1",
		NickNames = new[] { "Test1" }
	})
));

// Query Data times out killing the connection.
await redisCollection.Where(x=>x.NickNames.Contains("Test1")).ToListAsync().Dump();

```

**Comment by slorello89** [comment]
Yeah I think this is an issue with RediSearch that should be resolved see redisearch/redisearch#2803

**Comment by VagyokC4** [comment]
> Yeah I think this is an issue with RediSearch that should be resolved see [RediSearch/RediSearch#2803](https://github.com/RediSearch/RediSearch/issues/2803)

Yeah, I too thought this was already resolved.  Are you able to reproduce it on your side with the above code?  I'm using redis-stack-server:7.0.2-RC1 image over here, where that older fix has been migrated into.

**Comment by VagyokC4** [comment]
> > Yeah I think this is an issue with RediSearch that should be resolved see [RediSearch/RediSearch#2803](https://github.com/RediSearch/RediSearch/issues/2803)
> 
> Yeah, I too thought this was already resolved. Are you able to reproduce it on your side with the above code? I'm using redis-stack-server:7.0.2-RC1 image over here, where that older fix has been migrated into.

Also, I running with the following arg `REDISEARCH_ARGS="MAXSEARCHRESULTS -1"` and still experiencing this issue.

**Comment by VagyokC4** [comment]
Confirmed this issue goes away when running 7.0.2-RC2+ image.
